name: Check Links

on:
  schedule:
    - cron: '0 0 * * 0' # Chaque dimanche
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install linkinator
        run: npm install -g linkinator

      - name: Run link checker
        run: linkinator . --markdown --quiet
